### ISSUE TITLE
Bump @esri/calcite-ui-icons to 1.6.4

### ISSUE THREAD

**Issue by sandromartis** [jpeterson/calcite-ui-icons-react#3]
Could you bump `@esri/calcite-ui-icons` to `1.6.4` and publish to npm?

Thanks a lot :)

**Comment by lisastaehli** [comment]
@jpeterson we would need to have an updated version of `calcite-ui-icons` as soon as possible :) would you be able to make a new version and publish to npm? Thanks.

**Comment by jpeterson** [comment]
@sandromartis @lisastaehli so sorry I missed this request 😣 I will get an update published today.

**Comment by jpeterson** [comment]
This is done.

https://github.com/jpeterson/calcite-ui-icons-react/releases/tag/v0.4.0
